vim.wo.number = true
vim.o.clipboard = "unnamedplus"
vim.o.wrap = false
vim.o.spell = true
vim.o.swapfile = false
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.shiftwidth = 2
vim.o.tabstop = 2
vim.o.softtabstop = 2
vim.o.expandtab = true
vim.o.background = "dark"
vim.o.showmode = false
-- vim.o.signcolumn = "yes"
-- vim.o.statuscolumn = [[%!v:lua.require'util.ui'.statuscolumn()]]
vim.o.termguicolors = true
vim.o.smoothscroll = true
vim.o.splitright = true
